version: '3'

tasks:
  build:
    desc: Generate tmux configuration from extend.yml
    cmds:
      - mkdir -p hints
      - ruby tmux_gen.rb > extra.conf
    sources:
      - extend.yml
      - tmux_gen.rb
    generates:
      - extra.conf

  install:
    desc: Symlink this repo to ~/.config/tmux-gen and update .tmux.conf
    cmds:
      - ln -sfn {{.USER_WORKING_DIR}} ~/.config/tmux-gen
      - echo "Make sure to add 'source-file ~/.config/tmux-gen/extra.conf' to your ~/.tmux.conf"

  reload:
    desc: Build and source the new config
    deps: [build]
    cmds:
      - tmux source-file ~/.tmux.conf
      - tmux display-message "Tmux configuration reloaded!"

  default:
    desc: Build and reload
    cmds:
      - task: reload

