import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import * as yaml from 'js-yaml';
import { execSync } from 'child_process';
import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import { type Tree, type Entry, type Node, type TableSource, type TableDef, type TableBind, type ConfigStrategy } from './types.js';

export const CONFIG_DIR = path.resolve(process.env.HOME || '', '.config/extend');
export const CONFIG_JSON = path.join(CONFIG_DIR, 'config.json');

export interface AppConfig {
  renderers: {
    [key: string]: {
      enabled: boolean;
      source_path: string;
      output_path: string;
      prefix?: string;
      debug?: boolean;
    }
  }
}

export function loadConfig(): AppConfig {
  if (!fs.existsSync(CONFIG_JSON)) {
    return {
      renderers: {
        zsh: {
          enabled: true,
          source_path: path.join(CONFIG_DIR, 'zsh.extend.yml'),
          output_path: path.resolve(process.env.HOME || '', '.extend.zsh')
        },
        tmux: {
          enabled: true,
          source_path: path.join(CONFIG_DIR, 'tmux.extend.yml'),
          output_path: path.resolve(process.env.HOME || '', '.tmux.extend.conf')
        }
      }
    };
  }
  const content = fs.readFileSync(CONFIG_JSON, 'utf8');
  const config = JSON.parse(content) as AppConfig;
  Object.values(config.renderers).forEach(r => {
    r.source_path = r.source_path.replace(/^~/, process.env.HOME || '');
    r.output_path = r.output_path.replace(/^~/, process.env.HOME || '');
  });
  return config;
}

const appConfig = loadConfig();

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
export const SCHEMA_JSON = path.resolve(__dirname, '../../extend.schema.json');
const HINTS_DIR = path.resolve(__dirname, '../../hints');

const ajv = new Ajv({ allErrors: true, strict: false });
addFormats(ajv);

let schema: any = null;
try {
  schema = JSON.parse(fs.readFileSync(SCHEMA_JSON, 'utf8'));
} catch (e) {
  console.warn("Could not load schema for validation");
}

export function validateYaml(data: any) {
  if (!schema) return true;
  const validate = ajv.compile(schema);
  const valid = validate(data);
  if (!valid) {
    console.error("Validation errors:", validate.errors);
  }
  return valid;
}

export function resolveCommand(action: string | { [platform: string]: string } | undefined): string {
  if (!action) return "";
  if (typeof action === 'string') return action;
  const platform = process.platform;
  if (action[platform]) return action[platform];
  if (action['default']) return action['default'];
  const firstKey = Object.keys(action).find(k => k !== 'default');
  if (firstKey) return action[firstKey];
  return action['default'] || "";
}

export function loadTree(filePath: string): Tree {
  const content = fs.readFileSync(filePath, 'utf8');
  const source = yaml.load(content) as any;
  if (Array.isArray(source)) {
    validateYaml(source);
    return tableToTree(source, path.dirname(filePath));
  } else {
    return resolveBundles(source, path.dirname(filePath));
  }
}

export class ZshStrategy implements ConfigStrategy {
  id = 'zsh';
  mnemonicSeparator = '';
  getMnemonic(parent: string, key: string): string { return parent + key; }
  getEntryName(mnemonic: string, slugParts: string[]): string {
    const cleanSlug = slugParts.map(s => s.replace(/\s+/g, '-')).join('-');
    return `${mnemonic}-${cleanSlug}`;
  }
  splitMnemonic(mnemonic: string): string[] { return mnemonic.split(''); }
  getSourceCommand(outputPath: string): string { return `source ${outputPath}`; }
  render(tree: Tree): string {
    const allEntries = getAllEntries(tree, this);
    const mnemonicMap: { [key: string]: Entry[] } = {};
    allEntries.forEach(entry => {
      if (!mnemonicMap[entry.mnemonic]) mnemonicMap[entry.mnemonic] = [];
      mnemonicMap[entry.mnemonic].push(entry);
    });
    const output: string[] = ["# Generated from extend config", "# Do not edit this file directly", ""];
    const mnemonics = Object.keys(mnemonicMap);
    mnemonics.forEach(m => {
      try {
        const originalPath = execSync(`which ${m}`, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
        if (originalPath && !originalPath.includes('not found')) {
          output.push(`alias extend_original_${m}='${originalPath}'`);
        }
      } catch (e) { }
    });
    output.push("");
    allEntries.forEach(entry => {
      let cmd = entry.cmd;
      mnemonics.forEach(m => {
        const regex = new RegExp(`(^|\\s)${m}(\\s|$)`, 'g');
        if (regex.test(cmd)) {
          if (output.some(line => line.startsWith(`alias extend_original_${m}=`))) {
            cmd = cmd.replace(regex, `$1extend_original_${m}$2`);
          }
        }
      });
      switch (entry.type) {
        case 'export': output.push(cmd); break;
        case 'func':
          const names = [entry.name];
          if (entry.mnemonic !== entry.name && mnemonicMap[entry.mnemonic][0] === entry) {
            names.push(entry.mnemonic);
          }
          const namesStr = names.join(' ');
          if (cmd.includes('\n')) {
            output.push(`function ${namesStr} {`);
            cmd.split('\n').forEach(line => output.push(`  ${line}`));
            output.push(`}`);
          } else { output.push(`function ${namesStr} { ${cmd} }`); }
          break;
        case 'alias':
          output.push(`alias ${entry.name}='${cmd}' ${entry.comment}`);
          if (mnemonicMap[entry.mnemonic][0] === entry) output.push(`alias ${entry.mnemonic}='${cmd}'`);
          break;
      }
    });
    return output.join("\n");
  }
  sync() {
    const config = loadConfig();
    const zshConfig = config.renderers.zsh;
    if (!zshConfig || !zshConfig.enabled) return;
    const tree = loadTree(zshConfig.source_path);
    const content = this.render(tree);
    fs.writeFileSync(zshConfig.output_path, content);
    const allEntries = getAllEntries(tree, this);
    let maxMnemonic = 0, maxLabel = 0;
    allEntries.forEach(e => {
      const label = e.category ? `${e.category} -> ${e.description}` : e.description;
      if (e.mnemonic.length > maxMnemonic) maxMnemonic = e.mnemonic.length;
      if (label.length > maxLabel) maxLabel = label.length;
    });
    const hintLines = allEntries.map(e => {
      const label = e.category ? `${e.category} -> ${e.description}` : e.description;
      return `${e.mnemonic.padEnd(maxMnemonic)} │ ${label.padEnd(maxLabel)}`;
    });
    fs.writeFileSync(path.join(CONFIG_DIR, 'zsh_fzf_hints.txt'), hintLines.join("\n"));
  }
}

export class TmuxStrategy implements ConfigStrategy {
  id = 'tmux';
  mnemonicSeparator = '->';
  getMnemonic(parent: string, key: string): string { return parent ? `${parent}${this.mnemonicSeparator}${key}` : key; }
  getEntryName(mnemonic: string, slugParts: string[]): string { return slugParts.filter(s => s).map(s => s.replace(/\s+/g, '-')).join('-'); }
  splitMnemonic(mnemonic: string): string[] { return mnemonic.split(this.mnemonicSeparator); }
  getSourceCommand(outputPath: string): string { return `tmux source-file ${outputPath}`; }
  render(tree: Tree): string {
    const config = loadConfig();
    const tmuxConfig = config.renderers.tmux;
    const prefix = tmuxConfig?.prefix;
    let output = generateTmux(config.renderers.tmux.source_path);
    if (prefix) output = `bind-key -n ${prefix} switch-client -Troot\n` + output;
    return output;
  }
  sync() {
    const config = loadConfig();
    const tmuxConfig = config.renderers.tmux;
    if (!tmuxConfig || !tmuxConfig.enabled) return;
    const content = this.render({} as Tree);
    fs.writeFileSync(tmuxConfig.output_path, content);
  }
}

export class HammerspoonStrategy implements ConfigStrategy {
  id = 'hammerspoon';
  mnemonicSeparator = '';
  getMnemonic(parent: string, key: string): string { return parent + key; }
  getEntryName(mnemonic: string, slugParts: string[]): string { return slugParts.filter(s => s).map(s => s.replace(/\s+/g, '-')).join('-'); }
  splitMnemonic(mnemonic: string): string[] { return mnemonic.split(''); }
  getSourceCommand(outputPath: string): string { return `dofile("${outputPath}")`; }
  render(tree: Tree): string {
    const config = loadConfig();
    const hsConfig = config.renderers.hammerspoon;
    const leader = hsConfig?.prefix || "control-space";
    let leaderMod: string = "", leaderKey = "";
    if (leader.includes('-')) { const parts = leader.split('-'); leaderKey = parts.pop() || ""; leaderMod = parts + ""; }
    else { leaderKey = leader; }
    const output: string[] = ["-- Generated from extend config", "-- Do not edit this file directly", "", `local root = hs.hotkey.modal.new(${JSON.stringify(leaderMod)}, ${JSON.stringify(leaderKey)})`];
    const rootNodes: { [key: string]: Node } = {};
    Object.values(tree).forEach(nodes => {
      Object.entries(nodes).forEach(([key, node]) => {
        if (rootNodes[key]) {
          if (node.children) { if (!rootNodes[key].children) rootNodes[key].children = {}; Object.assign(rootNodes[key].children!, node.children); }
          if (node.exec) rootNodes[key].exec = node.exec;
        } else { rootNodes[key] = node; }
      });
    });
    if (hsConfig?.debug) {
      output.push("function root:entered() ", "  hs.alert.show('Extend Mode')", "  print('--- Extend Mode Root ---')");
      Object.entries(rootNodes).forEach(([key, node]) => { output.push(`  print('${key}: ${node.description || key}')`); });
      output.push("end");
    } else { output.push("function root:entered() hs.alert.show('Extend Mode') end"); }
    output.push("function root:exited() hs.alert.closeAll() end", 'root:bind("", "escape", function() root:exit() end)', "");

    const walk = (node: Node, modalStack: string[], modalPath: string) => {
      const parentModal = modalStack[modalStack.length - 1];
      if (node.children) {
        Object.entries(node.children).forEach(([key, child]) => {
          if (child.exec) {
            const cmd = resolveCommand(child.exec);
            const desc = child.description || key;
            const type = child.type;
            output.push(`${parentModal}:bind("", ${JSON.stringify(key)}, ${JSON.stringify(desc)}, function()`);
            if (type === 'function' || type === 'func' || cmd.includes('hs.') || cmd.includes('(')) { output.push(`  ${cmd.replace(/\n/g, '\n  ')}`); }
            else { output.push(`  hs.execute(${JSON.stringify(cmd)})`); }
            modalStack.slice().reverse().forEach(m => { output.push(`  ${m}:exit()`); });
            output.push("end)");
          } else if (child.children) {
            const modalName = `modal_${parentModal}_${key}`.replace(/[^a-zA-Z0-9_]/g, '_');
            const currentPath = `${modalPath} -> ${child.description || key}`;
            output.push(`local ${modalName} = hs.hotkey.modal.new()`);
            if (hsConfig?.debug) {
              output.push(`function ${modalName}:entered()`, `  print('--- ${currentPath} ---')`);
              Object.entries(child.children).forEach(([k, v]) => { output.push(`  print('${k}: ${v.description || k}')`); });
              output.push("end");
            }
            output.push(`${parentModal}:bind("", ${JSON.stringify(key)}, ${JSON.stringify(child.description || key)}, function() ${modalName}:enter() end)`);
            output.push(`${modalName}:bind("", "escape", function()`);
            modalStack.slice().reverse().forEach(m => { output.push(`  ${m}:exit()`); });
            output.push(`  ${modalName}:exit()`);
            output.push("end)");
            walk(child, [...modalStack, modalName], currentPath);
          }
        });
      }
    };
    Object.entries(rootNodes).forEach(([key, node]) => {
      if (node.exec) {
        const cmd = resolveCommand(node.exec);
        const type = node.type;
        output.push(`root:bind("", ${JSON.stringify(key)}, ${JSON.stringify(node.description || key)}, function()`);
        if (type === 'function' || type === 'func' || cmd.includes('hs.') || cmd.includes('(')) { output.push(`  ${cmd.replace(/\n/g, '\n  ')}`); }
        else { output.push(`  hs.execute(${JSON.stringify(cmd)})`); }
        output.push(`  root:exit()`, "end)");
      } else if (node.children) {
        const modalName = `modal_root_${key}`.replace(/[^a-zA-Z0-9_]/g, '_');
        const currentPath = `${node.description || key}`;
        output.push(`local ${modalName} = hs.hotkey.modal.new()`);
        if (hsConfig?.debug) {
          output.push(`function ${modalName}:entered()`, `  print('--- ${currentPath} ---')`);
          Object.entries(node.children).forEach(([k, v]) => { output.push(`  print('${k}: ${v.description || k}')`); });
          output.push("end");
        }
        output.push(`root:bind("", ${JSON.stringify(key)}, ${JSON.stringify(node.description || key)}, function() ${modalName}:enter() end)`);
        output.push(`${modalName}:bind("", "escape", function()`, `  ${modalName}:exit()`, `  root:exit()`, "end)");
        walk(node, ["root", modalName], currentPath);
      }
    });
    return output.join("\n");
  }
  sync() {
    const config = loadConfig();
    const hsConfig = config.renderers.hammerspoon;
    if (!hsConfig || !hsConfig.enabled) return;
    const tree = loadTree(hsConfig.source_path);
    const content = this.render(tree);
    fs.writeFileSync(hsConfig.output_path, content);
  }
}

export const STRATEGIES: { [key: string]: ConfigStrategy } = {
  zsh: new ZshStrategy(),
  tmux: new TmuxStrategy(),
  hammerspoon: new HammerspoonStrategy()
};

function tableToTree(source: TableSource, baseDir: string): Tree {
  const tables: { [name: string]: TableDef } = {};
  source.forEach(entry => { if (!entry) return; const entries = Object.entries(entry); if (entries.length === 0) return; const [name, def] = entries[0]; tables[name] = def; });
  const tree: Tree = {};
  const referencedTables = new Set<string>();
  Object.values(tables).forEach(def => { if (def && def.binds) { def.binds.forEach(bind => { if (bind.table) referencedTables.add(bind.table); }); } });
  const entryPoints = Object.keys(tables).filter(name => name === 'root' || name === 'prefix' || !referencedTables.has(name));
  entryPoints.forEach(name => {
    const tableDef = tables[name];
    if (!tableDef || !tableDef.binds) return;
    tableDef.binds.forEach(bind => {
      const category = bind.category || tableDef.description || name;
      if (!tree[category]) tree[category] = {};
      const node = bindToNode(bind, tables, baseDir);
      if (node.tableName === undefined) node.tableName = name;
      if (node.tableDescription === undefined) node.tableDescription = tableDef.description || name;
      if (tree[category][bind.key]) {
        const existingNode = tree[category][bind.key];
        if (!existingNode.children) existingNode.children = {};
        if (node.children) { Object.assign(existingNode.children, node.children); }
        if (node.exec) { if (typeof existingNode.exec === 'object' && typeof node.exec === 'object') { existingNode.exec = { ...existingNode.exec, ...node.exec }; } else { existingNode.exec = node.exec; } }
        if (node.description) existingNode.description = node.description;
      } else { tree[category][bind.key] = node; }
    });
  });
  return tree;
}

function bindToNode(bind: TableBind, tables: { [name: string]: TableDef }, baseDir: string): Node {
  const node: Node = { description: bind.description, type: bind.type };
  if (bind.action) { node.exec = bind.action; }
  if (bind.bundle) {
    const bundlePath = path.resolve(baseDir, bind.bundle);
    if (fs.existsSync(bundlePath)) {
      const bundleContent = fs.readFileSync(bundlePath, 'utf8');
      const bundleData = yaml.load(bundleContent) as any;
      node.children = bundleData.children;
      node.description = bundleData.description || node.description;
      node._source = bundlePath;
    }
  } else if (bind.table && tables[bind.table]) {
    const tableDef = tables[bind.table];
    node.children = {};
    node.tableName = bind.table;
    node.tableDescription = tableDef ? (tableDef.description || bind.description) : bind.description;
    if (tableDef && tableDef.binds) { tableDef.binds.forEach(childBind => { if (node.children) { node.children[childBind.key] = bindToNode(childBind, tables, baseDir); } }); }
  }
  return node;
}

export function saveTree(tree: Tree, filePath: string) {
  const tableSource = treeToTable(tree, filePath);
  const content = yaml.dump(tableSource, { indent: 2, lineWidth: -1 });
  fs.writeFileSync(filePath, content);
}

function treeToTable(tree: Tree, sourcePath: string): TableSource {
  const tables: TableSource = [];
  const rootBinds: TableBind[] = [];
  for (const [category, rootNodes] of Object.entries(tree)) {
    for (const [key, node] of Object.entries(rootNodes)) {
      const tableName = `table_${category}_${key}`.replace(/\./g, '_');
      const hasChildren = node.children && Object.keys(node.children).length > 0 && !node._source;
      rootBinds.push({
        key, table: hasChildren ? tableName : undefined, description: node.description, category,
        action: node.exec, type: node.type as any,
        bundle: node._source ? path.relative(path.dirname(sourcePath), node._source) : undefined
      });
      if (hasChildren && node.children) { nodeToTable(tableName, node.children, [category, key], tables, sourcePath); }
    }
  }
  tables.unshift({ root: { binds: rootBinds } });
  return tables;
}

function nodeToTable(name: string, children: { [key: string]: Node }, nodePath: string[], tables: TableSource, sourcePath: string) {
  const binds: TableBind[] = [];
  for (const [key, node] of Object.entries(children)) {
    const currentPath = [...nodePath, key];
    const tableName = `table_${currentPath.join('_')}`.replace(/\./g, '_');
    const hasChildren = node.children && Object.keys(node.children).length > 0 && !node._source;
    binds.push({
      key, table: hasChildren ? tableName : undefined, description: node.description, action: node.exec, type: node.type as any,
      bundle: node._source ? path.relative(path.dirname(sourcePath), node._source) : undefined
    });
    if (hasChildren && node.children) { nodeToTable(tableName, node.children, currentPath, tables, sourcePath); }
  }
  tables.push({ [name]: { binds } });
}

export function walk(node: Node, mnemonic: string = "", slugParts: string[] = [], category: string, strategy: ConfigStrategy, currentTable?: string, currentDescription?: string): Entry[] {
  let entries: Entry[] = [];
  const effectiveTable = node.tableName || currentTable;
  const effectiveDescription = node.tableDescription || currentDescription;
  if (node.exec) {
    const cmd = resolveCommand(node.exec);
    const fullName = strategy.getEntryName(mnemonic, slugParts);
    const comment = `# ${mnemonic}: ${slugParts.join(' -> ')}`;
    const fullPath = slugParts.slice(0, -1).join(' -> ');
    const getEntryType = (cmdStr: string, explicitType?: string): 'alias' | 'func' | 'export' => {
      if (explicitType === 'alias') return 'alias';
      if (explicitType === 'function' || explicitType === 'func') return 'func';
      if (explicitType === 'export') return 'export';
      if (cmdStr.startsWith("export ")) return 'export';
      if (cmdStr.includes(';') || cmdStr.includes('$') || cmdStr.includes('if ') || cmdStr.includes('\n')) return 'func';
      return 'alias';
    };
    entries.push({ type: getEntryType(cmd, node.type), mnemonic, name: fullName, cmd, comment, category: fullPath || effectiveDescription || effectiveTable || category, rootCategory: category, description: node.description || "", source: (node as any)._source, node: node });
  }
  if (node.children) { for (const [key, child] of Object.entries(node.children)) { const nextMnemonic = strategy.getMnemonic(mnemonic, key); entries = entries.concat(walk(child, nextMnemonic, [...slugParts, child.description || ""], category, strategy, effectiveTable, effectiveDescription)); } }
  return entries;
}

export function getAllEntries(tree: Tree, strategy: ConfigStrategy): Entry[] {
  let allEntries: Entry[] = [];
  for (const [category, rootNodes] of Object.entries(tree)) {
    if (typeof rootNodes !== 'object') continue;
    for (const [key, node] of Object.entries(rootNodes)) {
      const initialTable = category === 'unknown' ? undefined : category;
      allEntries = allEntries.concat(walk(node, key, [node.description || ""], category, strategy, initialTable, node.tableDescription));
    }
  }
  return allEntries;
}

export function syncZsh() { STRATEGIES.zsh.sync(); }
export function syncTmux() { STRATEGIES.tmux.sync(); }

function resolveBundles(tree: any, baseDir: string, parentTable?: string, parentDescription?: string): any {
  if (typeof tree !== 'object' || tree === null) return tree;
  const resolved: any = Array.isArray(tree) ? [] : {};
  for (const [key, value] of Object.entries(tree)) {
    let node = value as any;
    if (node && typeof node === 'object' && node.bundle) {
      const bundlePath = path.resolve(baseDir, node.bundle);
      if (fs.existsSync(bundlePath)) {
        const bundleContent = fs.readFileSync(bundlePath, 'utf8');
        const bundleData = yaml.load(bundleContent) as any;
        node = { ...node, ...bundleData, _source: bundlePath };
        delete node.bundle;
      }
    }
    if (node && typeof node === 'object') {
      const currentTable = node.tableName || parentTable || (parentTable === undefined ? key : undefined);
      const currentDescription = node.tableDescription || parentDescription || (parentDescription === undefined ? (node.description || key) : undefined);
      resolved[key] = resolveBundles(node, baseDir, currentTable, currentDescription);
      if (resolved[key] && typeof resolved[key] === 'object') {
        if (resolved[key].tableName === undefined) resolved[key].tableName = currentTable;
        if (resolved[key].tableDescription === undefined) resolved[key].tableDescription = currentDescription;
      }
    } else { resolved[key] = node; }
  }
  return resolved;
}

export function generateTmux(filePath: string): string {
  const content = fs.readFileSync(filePath, 'utf8');
  const smartSwitch = path.resolve(__dirname, '../../smart_session_switch.rb');
  const helperScript = path.resolve(__dirname, '../../tmux_mode_helper.rb');
  let dataContent = content.replace(/#\{smart_session_switch\}/g, smartSwitch);
  const rawData = yaml.load(dataContent) as TableSource;
  const data = resolveBundlesForTmux(rawData, path.dirname(filePath));
  const tableMnemonics = calculateTableMnemonics(data);
  const allBindsForPalette: string[] = [];
  const allGenerated = data.map(entry => {
    if (!entry) return "";
    const [name, tableData] = Object.entries(entry)[0];
    const modal = tableData.modal === true;
    const validBinds = tableData.binds.filter(bind => { if (!bind.dependency) return true; try { execSync(`which ${bind.dependency}`, { stdio: 'ignore' }); return true; } catch (e) { return false; } });
    const tableMnemonic = tableMnemonics[name] || "";
    const tableDescription = tableData.description || name;
    const hintLines = validBinds.map(b => { if (name !== 'root') { allBindsForPalette.push(formatAllBind(name, tableDescription, tableMnemonic, b)); } return formatBind(b); });
    if (!fs.existsSync(HINTS_DIR)) fs.mkdirSync(HINTS_DIR, { recursive: true });
    fs.writeFileSync(path.join(HINTS_DIR, `${name}.txt`), hintLines.join("\n"));
    const lines: string[] = [];
    lines.push(`# table: ${name}`, `# modal: ${modal}`);
    if (name !== 'root' && name !== 'prefix') {
      lines.push(`if-shell 'tmux list-keys -T${name} >/dev/null 2>&1' 'unbind-key -a -T${name}'`);
      const rubyBin = process.platform === 'darwin' ? '/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby' : 'ruby';
      lines.push(`bind-key -T${name} ? display-popup -E -w 80% -h 40% "${rubyBin} --disable-gems ${helperScript} fuzzy ${name}"`);
    }
    validBinds.forEach(bind => {
      const key = bind.key;
      let action = (name === 'extend' && key === 'h') ? `display-popup -E -w 90% -h 60% "/usr/bin/ruby --disable-gems ${helperScript} palette"` : getTmuxAction(bind, name, modal);
      lines.push(`bind-key -T${name} ${key} ${action}`);
    });
    return lines.join("\n");
  });
  fs.writeFileSync(path.join(HINTS_DIR, "all.txt"), allBindsForPalette.join("\n"));
  return allGenerated.join("\n");
}

function resolveBundlesForTmux(entries: TableSource, baseDir: string): TableSource {
  const resolved: TableSource = [];
  const queue = [...entries];
  const processed: { [key: string]: boolean } = {};
  while (queue.length > 0) {
    const entry = queue.shift()!; if (!entry) continue;
    const [name, tableData] = Object.entries(entry)[0];
    if (processed[name]) continue;
    if (tableData.mount === false) { processed[name] = true; continue; }
    processed[name] = true;
    const newBinds: TableBind[] = [];
    if (tableData && tableData.binds) {
      tableData.binds.forEach(bind => {
        if (bind.mount === false) return;
        if (bind.bundle) {
          const bundlePath = path.resolve(baseDir, bind.bundle);
          if (fs.existsSync(bundlePath)) {
            const bundleContent = yaml.load(fs.readFileSync(bundlePath, 'utf8')) as any;
            const bundleName = path.basename(bundlePath, '.extend.yml');
            newBinds.push({ key: bind.key, table: bundleName, description: bind.description || bundleContent.description || bundleName });
            if (!processed[bundleName] && !queue.find(e => e && Object.keys(e)[0] === bundleName)) {
              const bundleTableBinds: TableBind[] = [];
              if (bundleContent.children) {
                Object.entries(bundleContent.children).forEach(([k, v]: [string, any]) => {
                  if (typeof v === 'object') { bundleTableBinds.push({ key: k, type: v.exec ? 'exec' : (v.send ? 'send' : undefined), action: v.exec || v.send || v.action, description: v.description }); }
                  else { bundleTableBinds.push({ key: k, action: v }); }
                });
              }
              queue.push({ [bundleName]: { binds: bundleTableBinds, modal: true, description: bundleContent.description } });
            }
          }
        } else { newBinds.push(bind); }
      });
    }
    resolved.push({ [name]: { ...tableData, binds: newBinds } });
  }
  return resolved;
}

function calculateTableMnemonics(data: TableSource): { [tableName: string]: string } {
  const tableToMnemonic: { [name: string]: string } = { root: "", prefix: "" };
  const queue = ["root", "prefix"];
  const visited = new Set(queue);
  const strategy = STRATEGIES.tmux;
  while (queue.length > 0) {
    const currentName = queue.shift()!;
    const entry = data.find(e => e && Object.keys(e)[0] === currentName);
    if (!entry) continue;
    const tableData = entry[currentName];
    const currentMnemonic = tableToMnemonic[currentName];
    tableData.binds.forEach(bind => {
      if (bind.table) {
        const nextMnemonic = strategy.getMnemonic(currentMnemonic, bind.key);
        if (!tableToMnemonic[bind.table]) {
          tableToMnemonic[bind.table] = nextMnemonic;
          if (!visited.has(bind.table)) { visited.add(bind.table); queue.push(bind.table); }
        }
      }
    });
  }
  return tableToMnemonic;
}

function formatBind(bind: TableBind): string {
  const key = bind.key;
  const action = bind.action || `Mode: ${bind.table}`;
  const desc = bind.description || "";
  return `${key.padEnd(8)} │ ${desc.padEnd(35)} │ ${action}`;
}

function formatAllBind(tableName: string, tableDescription: string, tableMnemonic: string, bind: TableBind): string {
  const key = bind.key;
  const action = bind.action || `Mode: ${bind.table}`;
  const desc = bind.description || "";
  const strategy = STRATEGIES.tmux;
  const fullMnemonic = strategy.getMnemonic(tableMnemonic, key);
  return `${fullMnemonic.padEnd(25)} │ ${desc.padEnd(45)} │ ${tableDescription.padEnd(20)} │ ${tableName}:${key} │ ${action}`;
}

function getTmuxAction(bind: TableBind, tableName: string, isModal: boolean): string {
  let action = resolveCommand(bind.action);
  if (!action && bind.table) { return `switch-client -T${bind.table} \\; display-message '${bind.table}'`; }
  switch (bind.type) {
    case 'exec': action = `send-keys ${escapeShell(action)} Enter`; break;
    case 'send': action = `send-keys ${escapeShell(action)}`; break;
    case 'test': action = `display-message ${escapeShell(action)}`; break;
    case 'run': action = `run -b ${escapeShell(action)}`; break;
  }
  if (isModal) { action += ` \\; switch-client -T${tableName}`; }
  return action;
}

function escapeShell(cmd: string): string { return `"${cmd}"` }
