import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';
import * as yaml from 'js-yaml';
import { execSync } from 'child_process';
import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import { type Tree, type Entry, type Node, type TableSource, type TableDef, type TableBind, type ConfigStrategy } from './types.js';

export const CONFIG_DIR = path.resolve(process.env.HOME || '', '.config/extend');
export const CONFIG_JSON = path.join(CONFIG_DIR, 'config.json');

export interface AppConfig {
  renderers: {
    [key: string]: {
      enabled: boolean;
      source_path: string;
      output_path: string;
    }
  }
}

export function loadConfig(): AppConfig {
  if (!fs.existsSync(CONFIG_JSON)) {
    // Default config if not exists
    return {
      renderers: {
        zsh: {
          enabled: true,
          source_path: path.join(CONFIG_DIR, 'zsh.extend.yml'),
          output_path: path.resolve(process.env.HOME || '', '.extend.zsh')
        },
        tmux: {
          enabled: true,
          source_path: path.join(CONFIG_DIR, 'tmux.extend.yml'),
          output_path: path.resolve(process.env.HOME || '', '.tmux.extend.conf')
        }
      }
    };
  }
  const content = fs.readFileSync(CONFIG_JSON, 'utf8');
  // Handle ~ in paths
  const config = JSON.parse(content) as AppConfig;
  Object.values(config.renderers).forEach(r => {
    r.source_path = r.source_path.replace(/^~/, process.env.HOME || '');
    r.output_path = r.output_path.replace(/^~/, process.env.HOME || '');
  });
  return config;
}

const appConfig = loadConfig();

export const SCHEMA_JSON = path.resolve(__dirname, '../../extend.schema.json');
const HINTS_DIR = path.resolve(__dirname, '../../hints');

const ajv = new Ajv({ allErrors: true, strict: false });
addFormats(ajv);

let schema: any = null;
try {
  schema = JSON.parse(fs.readFileSync(SCHEMA_JSON, 'utf8'));
} catch (e) {
  console.warn("Could not load schema for validation");
}

export function validateYaml(data: any) {
  if (!schema) return true;
  const validate = ajv.compile(schema);
  const valid = validate(data);
  if (!valid) {
    console.error("Validation errors:", validate.errors);
  }
  return valid;
}

export function resolveCommand(action: string | { [platform: string]: string } | undefined): string {
  if (!action) return "";
  if (typeof action === 'string') return action;
  
  const platform = process.platform;
  if (action[platform]) return action[platform];
  if (action['default']) return action['default'];
  
  // Fallback to first available key if platform not found
  const firstKey = Object.keys(action).find(k => k !== 'default');
  if (firstKey) return action[firstKey];
  return action['default'] || "";
}

export function loadTree(filePath: string): Tree {
  const content = fs.readFileSync(filePath, 'utf8');
  const source = yaml.load(content) as any;
  
  if (Array.isArray(source)) {
    validateYaml(source);
    return tableToTree(source, path.dirname(filePath));
  } else {
    return resolveBundles(source, path.dirname(filePath));
  }
}

export class ZshStrategy implements ConfigStrategy {
  id = 'zsh';
  mnemonicSeparator = '';

  getMnemonic(parent: string, key: string): string {
    return parent + key;
  }

  getEntryName(mnemonic: string, slugParts: string[]): string {
    const cleanSlug = slugParts.map(s => s.replace(/\s+/g, '-')).join('-');
    return `${mnemonic}-${cleanSlug}`;
  }

  splitMnemonic(mnemonic: string): string[] {
    return mnemonic.split('');
  }

  getSourceCommand(outputPath: string): string {
    return `source ${outputPath}`;
  }

  render(tree: Tree): string {
    const allEntries = getAllEntries(tree, this);
    const mnemonicMap: { [key: string]: Entry[] } = {};

    allEntries.forEach(entry => {
      if (!mnemonicMap[entry.mnemonic]) mnemonicMap[entry.mnemonic] = [];
      mnemonicMap[entry.mnemonic].push(entry);
    });

    const output: string[] = [
      "# Generated from extend config",
      "# Do not edit this file directly",
      ""
    ];

    // 1. Capture original commands for mnemonics that exist in the system
    const mnemonics = Object.keys(mnemonicMap);
    mnemonics.forEach(m => {
      try {
        const originalPath = execSync(`which ${m}`, { encoding: 'utf8', stdio: ['ignore', 'pipe', 'ignore'] }).trim();
        if (originalPath && !originalPath.includes('not found')) {
           output.push(`alias extend_original_${m}='${originalPath}'`);
        }
      } catch (e) {
        // Command doesn't exist, ignore
      }
    });
    output.push("");

    // 2. Render entries, swapping system commands for our preserved ones
    allEntries.forEach(entry => {
      let cmd = entry.cmd;
      
      // If the command is exactly one of our short mnemonics, and we preserved it
      mnemonics.forEach(m => {
        const regex = new RegExp(`(^|\\s)${m}(\\s|$)`, 'g');
        if (regex.test(cmd)) {
           // Only replace if we actually defined a preservation alias for it
           if (output.some(line => line.startsWith(`alias extend_original_${m}=`))) {
             cmd = cmd.replace(regex, `$1extend_original_${m}$2`);
           }
        }
      });

      switch (entry.type) {
        case 'export':
          output.push(cmd);
          break;
        case 'func':
          output.push(`function ${entry.name} { ${cmd} }`);
          if (mnemonicMap[entry.mnemonic][0] === entry) {
            output.push(`alias ${entry.mnemonic}=${entry.name}`);
          }
          break;
        case 'alias':
          output.push(`alias ${entry.name}='${cmd}' ${entry.comment}`);
          if (mnemonicMap[entry.mnemonic][0] === entry) {
            output.push(`alias ${entry.mnemonic}='${cmd}'`);
          }
          break;
      }
    });

    return output.join("\n");
  }

  sync() {
    const config = loadConfig();
    const zshConfig = config.renderers.zsh;
    if (!zshConfig || !zshConfig.enabled) return;

    const tree = loadTree(zshConfig.source_path);
    const content = this.render(tree);
    fs.writeFileSync(zshConfig.output_path, content);

    // Generate fzf hint file
    const allEntries = getAllEntries(tree, this);
    
    // Calculate max widths for alignment
    let maxMnemonic = 0;
    let maxLabel = 0;
    
    allEntries.forEach(e => {
      const label = `${e.category} -> ${e.description}`;
      if (e.mnemonic.length > maxMnemonic) maxMnemonic = e.mnemonic.length;
      if (label.length > maxLabel) maxLabel = label.length;
    });

    const hintLines = allEntries.map(e => {
      const label = e.category ? `${e.category} -> ${e.description}` : e.description;
      const mnemonic = e.mnemonic.padEnd(maxMnemonic);
      const alignedLabel = label.padEnd(maxLabel);
      return `${mnemonic} │ ${alignedLabel}`;
    });
    
    const hintPath = path.join(CONFIG_DIR, 'zsh_fzf_hints.txt');
    fs.writeFileSync(hintPath, hintLines.join("\n"));
  }
}

export class TmuxStrategy implements ConfigStrategy {
  id = 'tmux';
  mnemonicSeparator = '->';

  getMnemonic(parent: string, key: string): string {
    return parent ? `${parent}${this.mnemonicSeparator}${key}` : key;
  }

  getEntryName(mnemonic: string, slugParts: string[]): string {
    return slugParts.filter(s => s).map(s => s.replace(/\s+/g, '-')).join('-');
  }

  splitMnemonic(mnemonic: string): string[] {
    return mnemonic.split(this.mnemonicSeparator);
  }

  getSourceCommand(outputPath: string): string {
    return `tmux source-file ${outputPath}`;
  }

  render(tree: Tree): string {
    const config = loadConfig();
    return generateTmux(config.renderers.tmux.source_path);
  }

  sync() {
    const config = loadConfig();
    const tmuxConfig = config.renderers.tmux;
    if (!tmuxConfig || !tmuxConfig.enabled) return;

    const content = this.render({} as Tree);
    fs.writeFileSync(tmuxConfig.output_path, content);
  }
}

export const STRATEGIES: { [key: string]: ConfigStrategy } = {
  zsh: new ZshStrategy(),
  tmux: new TmuxStrategy()
};

function tableToTree(source: TableSource, baseDir: string): Tree {
  const tables: { [name: string]: TableDef } = {};
  source.forEach(entry => {
    if (!entry) return;
    const entries = Object.entries(entry);
    if (entries.length === 0) return;
    const [name, def] = entries[0];
    tables[name] = def;
  });

  const tree: Tree = {};

  const referencedTables = new Set<string>();
  Object.values(tables).forEach(def => {
    if (def && def.binds) {
      def.binds.forEach(bind => {
        if (bind.table) referencedTables.add(bind.table);
      });
    }
  });

  const entryPoints = Object.keys(tables).filter(name => 
    name === 'root' || name === 'prefix' || !referencedTables.has(name)
  );

  entryPoints.forEach(name => {
    const tableDef = tables[name];
    if (!tableDef || !tableDef.binds) return;

    tableDef.binds.forEach(bind => {
      const category = bind.category || tableDef.description || name;
      if (!tree[category]) tree[category] = {};
      
      const node = bindToNode(bind, tables, baseDir);
      if (node.tableName === undefined) node.tableName = name;
      if (node.tableDescription === undefined) node.tableDescription = tableDef.description || name;

      // Merge nodes with same key to support multiple definitions
      if (tree[category][bind.key]) {
        const existingNode = tree[category][bind.key];
        if (!existingNode.children) existingNode.children = {};
        if (node.children) {
          Object.assign(existingNode.children, node.children);
        }
        if (node.exec) {
          if (typeof existingNode.exec === 'object' && typeof node.exec === 'object') {
            existingNode.exec = { ...existingNode.exec, ...node.exec };
          } else {
            existingNode.exec = node.exec;
          }
        }
        if (node.description) existingNode.description = node.description;
      } else {
        tree[category][bind.key] = node;
      }
    });
  });

  return tree;
}

function bindToNode(bind: TableBind, tables: { [name: string]: TableDef }, baseDir: string): Node {
  const node: Node = {
    description: bind.description,
  };

  if (bind.action) {
    node.exec = bind.action;
  }

  if (bind.bundle) {
    const bundlePath = path.resolve(baseDir, bind.bundle);
    if (fs.existsSync(bundlePath)) {
      const bundleContent = fs.readFileSync(bundlePath, 'utf8');
      const bundleData = yaml.load(bundleContent) as any;
      node.children = bundleData.children;
      node.description = bundleData.description || node.description;
      node._source = bundlePath;
    }
  } else if (bind.table && tables[bind.table]) {
    const tableDef = tables[bind.table];
    node.children = {};
    node.tableName = bind.table;
    node.tableDescription = tableDef ? (tableDef.description || bind.description) : bind.description;
    if (tableDef && tableDef.binds) {
      tableDef.binds.forEach(childBind => {
        if (node.children) {
          node.children[childBind.key] = bindToNode(childBind, tables, baseDir);
        }
      });
    }
  }

  return node;
}

export function saveTree(tree: Tree, filePath: string) {
  const tableSource = treeToTable(tree, filePath);
  const content = yaml.dump(tableSource, { indent: 2, lineWidth: -1 });
  fs.writeFileSync(filePath, content);
}

function treeToTable(tree: Tree, sourcePath: string): TableSource {
  const tables: TableSource = [];
  const rootBinds: TableBind[] = [];
  
  for (const [category, rootNodes] of Object.entries(tree)) {
    for (const [key, node] of Object.entries(rootNodes)) {
      const tableName = `table_${category}_${key}`.replace(/\./g, '_');
      const hasChildren = node.children && Object.keys(node.children).length > 0 && !node._source;
      
      rootBinds.push({
        key,
        table: hasChildren ? tableName : undefined,
        description: node.description,
        category,
        action: node.exec,
        type: node.exec ? 'exec' : undefined,
        bundle: node._source ? path.relative(path.dirname(sourcePath), node._source) : undefined
      });
      
      if (hasChildren && node.children) {
        nodeToTable(tableName, node.children, [category, key], tables, sourcePath);
      }
    }
  }

  tables.unshift({ root: { binds: rootBinds } });
  return tables;
}

function nodeToTable(name: string, children: { [key: string]: Node }, nodePath: string[], tables: TableSource, sourcePath: string) {
  const binds: TableBind[] = [];
  
  for (const [key, node] of Object.entries(children)) {
    const currentPath = [...nodePath, key];
    const tableName = `table_${currentPath.join('_')}`.replace(/\./g, '_');
    const hasChildren = node.children && Object.keys(node.children).length > 0 && !node._source;
    
    binds.push({
      key,
      table: hasChildren ? tableName : undefined,
      description: node.description,
      action: node.exec,
      type: node.exec ? 'exec' : undefined,
      bundle: node._source ? path.relative(path.dirname(sourcePath), node._source) : undefined
    });
    
    if (hasChildren && node.children) {
      nodeToTable(tableName, node.children, currentPath, tables, sourcePath);
    }
  }
  
  tables.push({ [name]: { binds } });
}

export function walk(node: Node, mnemonic: string = "", slugParts: string[] = [], category: string, strategy: ConfigStrategy, currentTable?: string, currentDescription?: string): Entry[] {
  let entries: Entry[] = [];
  const effectiveTable = node.tableName || currentTable;
  const effectiveDescription = node.tableDescription || currentDescription;

  if (node.exec) {
    const cmd = resolveCommand(node.exec);
    const fullName = strategy.getEntryName(mnemonic, slugParts);
    const comment = `# ${mnemonic}: ${slugParts.join(' -> ')}`;
    const fullPath = slugParts.slice(0, -1).join(' -> ');

    entries.push({ 
      type: cmd.startsWith("export ") ? 'export' : (cmd.includes(';') || cmd.includes('$') || cmd.includes('if ') ? 'func' : 'alias'),
      mnemonic, 
      name: fullName, 
      cmd, 
      comment, 
      category: fullPath || effectiveDescription || effectiveTable || category,
      description: node.description || "",
      source: (node as any)._source,
      node: node
    });
  }

  if (node.children) {
    for (const [key, child] of Object.entries(node.children)) {
      const nextMnemonic = strategy.getMnemonic(mnemonic, key);
      entries = entries.concat(walk(child, nextMnemonic, [...slugParts, child.description || ""], category, strategy, effectiveTable, effectiveDescription));
    }
  }

  return entries;
}

export function getAllEntries(tree: Tree, strategy: ConfigStrategy): Entry[] {
  let allEntries: Entry[] = [];
  for (const [category, rootNodes] of Object.entries(tree)) {
    if (typeof rootNodes !== 'object') continue;
    
    for (const [key, node] of Object.entries(rootNodes)) {
      const initialTable = category === 'unknown' ? undefined : category;
      allEntries = allEntries.concat(walk(node, key, [node.description || ""], category, strategy, initialTable, node.tableDescription));
    }
  }
  return allEntries;
}

export function syncZsh() {
  STRATEGIES.zsh.sync();
}

export function syncTmux() {
  STRATEGIES.tmux.sync();
}

function resolveBundles(tree: any, baseDir: string, parentTable?: string, parentDescription?: string): any {
  if (typeof tree !== 'object' || tree === null) return tree;
  const resolved: any = Array.isArray(tree) ? [] : {};
  for (const [key, value] of Object.entries(tree)) {
    let node = value as any;
    if (node && typeof node === 'object' && node.bundle) {
      const bundlePath = path.resolve(baseDir, node.bundle);
      if (fs.existsSync(bundlePath)) {
        const bundleContent = fs.readFileSync(bundlePath, 'utf8');
        const bundleData = yaml.load(bundleContent) as any;
        node = { ...node, ...bundleData, _source: bundlePath };
        delete node.bundle;
      }
    }
    if (node && typeof node === 'object') {
      const currentTable = node.tableName || parentTable || (parentTable === undefined ? key : undefined);
      const currentDescription = node.tableDescription || parentDescription || (parentDescription === undefined ? (node.description || key) : undefined);
      
      resolved[key] = resolveBundles(node, baseDir, currentTable, currentDescription);
      if (resolved[key] && typeof resolved[key] === 'object') {
        if (resolved[key].tableName === undefined) resolved[key].tableName = currentTable;
        if (resolved[key].tableDescription === undefined) resolved[key].tableDescription = currentDescription;
      }
    } else {
      resolved[key] = node;
    }
  }
  return resolved;
}

// TMUX GENERATION PORT

export function generateTmux(filePath: string): string {
  const content = fs.readFileSync(filePath, 'utf8');
  const smartSwitch = path.resolve(__dirname, '../../smart_session_switch.rb');
  const helperScript = path.resolve(__dirname, '../../tmux_mode_helper.rb');
  
  let dataContent = content.replace(/#\{smart_session_switch\}/g, smartSwitch);
  const rawData = yaml.load(dataContent) as TableSource;
  
  const data = resolveBundlesForTmux(rawData, path.dirname(filePath));
  const tableMnemonics = calculateTableMnemonics(data);
  const allBindsForPalette: string[] = [];
  
  const allGenerated = data.map(entry => {
    if (!entry) return "";
    const [name, tableData] = Object.entries(entry)[0];
    const modal = tableData.modal === true;
    
    const validBinds = tableData.binds.filter(bind => {
       if (!bind.dependency) return true;
       try {
         execSync(`which ${bind.dependency}`, { stdio: 'ignore' });
         return true;
       } catch (e) {
         return false;
       }
    });

    const tableMnemonic = tableMnemonics[name] || "";
    const tableDescription = tableData.description || name;
    const hintLines = validBinds.map(b => {
      if (name !== 'root') {
        allBindsForPalette.push(formatAllBind(name, tableDescription, tableMnemonic, b));
      }
      return formatBind(b);
    });
    
    if (!fs.existsSync(HINTS_DIR)) fs.mkdirSync(HINTS_DIR, { recursive: true });
    fs.writeFileSync(path.join(HINTS_DIR, `${name}.txt`), hintLines.join("\n"));
    
    const lines: string[] = [];
    lines.push(`# table: ${name}`);
    lines.push(`# modal: ${modal}`);
    if (name !== 'root' && name !== 'prefix') {
       lines.push(`unbind-key -a -T${name}`);
       const rubyBin = process.platform === 'darwin' ? '/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby' : 'ruby';
       lines.push(`bind-key -T${name} ? display-popup -E -w 80% -h 40% "${rubyBin} --disable-gems ${helperScript} fuzzy ${name}"`);
    }

    validBinds.forEach(bind => {
      const key = bind.key;
      let action = "";
      if (name === 'extend' && key === 'h') {
        const rubyBin = process.platform === 'darwin' ? '/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby' : 'ruby';
        action = `display-popup -E -w 90% -h 60% "${rubyBin} --disable-gems ${helperScript} palette"`;
      } else {
        action = getTmuxAction(bind, name, modal);
      }
      lines.push(`bind-key -T${name} ${key} ${action}`);
    });
    
    return lines.join("\n");
  });

  fs.writeFileSync(path.join(HINTS_DIR, "all.txt"), allBindsForPalette.join("\n"));
  return allGenerated.join("\n");
}

function resolveBundlesForTmux(entries: TableSource, baseDir: string): TableSource {
  const resolved: TableSource = [];
  const queue = [...entries];
  const processed: { [key: string]: boolean } = {};

  while (queue.length > 0) {
    const entry = queue.shift()!;
    if (!entry) continue;
    const [name, tableData] = Object.entries(entry)[0];
    if (processed[name]) continue;
    if (tableData.mount === false) {
      processed[name] = true;
      continue;
    }
    processed[name] = true;

    const newBinds: TableBind[] = [];
    if (tableData && tableData.binds) {
      tableData.binds.forEach(bind => {
        if (bind.mount === false) return;

        if (bind.bundle) {
          const bundlePath = path.resolve(baseDir, bind.bundle);
          if (fs.existsSync(bundlePath)) {
            const bundleContent = yaml.load(fs.readFileSync(bundlePath, 'utf8')) as any;
            const bundleName = path.basename(bundlePath, '.extend.yml');
            
            newBinds.push({
              key: bind.key,
              table: bundleName,
              description: bind.description || bundleContent.description || bundleName
            });

            if (!processed[bundleName] && !queue.find(e => e && Object.keys(e)[0] === bundleName)) {
              const bundleTableBinds: TableBind[] = [];
              if (bundleContent.children) {
                Object.entries(bundleContent.children).forEach(([k, v]: [string, any]) => {
                  if (typeof v === 'object') {
                    bundleTableBinds.push({
                      key: k,
                      type: v.exec ? 'exec' : (v.send ? 'send' : undefined),
                      action: v.exec || v.send || v.action,
                      description: v.description
                    });
                  } else {
                    bundleTableBinds.push({ key: k, action: v });
                  }
                });
              }
              queue.push({ [bundleName]: { binds: bundleTableBinds, modal: true, description: bundleContent.description } });
            }
          }
        } else {
          newBinds.push(bind);
        }
      });
    }
    
    resolved.push({ [name]: { ...tableData, binds: newBinds } });
  }
  return resolved;
}

function calculateTableMnemonics(data: TableSource): { [tableName: string]: string } {
  const tableToMnemonic: { [name: string]: string } = { root: "", prefix: "" };
  const queue = ["root", "prefix"];
  const visited = new Set(queue);
  const strategy = STRATEGIES.tmux;

  while (queue.length > 0) {
    const currentName = queue.shift()!;
    const entry = data.find(e => e && Object.keys(e)[0] === currentName);
    if (!entry) continue;
    const tableData = entry[currentName];
    const currentMnemonic = tableToMnemonic[currentName];

    tableData.binds.forEach(bind => {
      if (bind.table) {
        const nextMnemonic = strategy.getMnemonic(currentMnemonic, bind.key);
        if (!tableToMnemonic[bind.table]) {
          tableToMnemonic[bind.table] = nextMnemonic;
          if (!visited.has(bind.table)) {
            visited.add(bind.table);
            queue.push(bind.table);
          }
        }
      }
    });
  }
  return tableToMnemonic;
}

function formatBind(bind: TableBind): string {
  const key = bind.key;
  const action = bind.action || `Mode: ${bind.table}`;
  const desc = bind.description || "";
  return `${key.padEnd(8)} │ ${desc.padEnd(35)} │ ${action}`;
}

function formatAllBind(tableName: string, tableDescription: string, tableMnemonic: string, bind: TableBind): string {
  const key = bind.key;
  const action = bind.action || `Mode: ${bind.table}`;
  const desc = bind.description || "";
  const strategy = STRATEGIES.tmux;
  const fullMnemonic = strategy.getMnemonic(tableMnemonic, key);
  return `${fullMnemonic.padEnd(25)} │ ${desc.padEnd(45)} │ ${tableDescription.padEnd(20)} │ ${tableName}:${key} │ ${action}`;
}

function getTmuxAction(bind: TableBind, tableName: string, isModal: boolean): string {
  let action = resolveCommand(bind.action);
  
  if (!action && bind.table) {
    return `switch-client -T${bind.table} \\; display-message '${bind.table}'`;
  }

  switch (bind.type) {
    case 'exec':
      action = `send-keys ${escapeShell(action)} Enter`;
      break;
    case 'send':
      action = `send-keys ${escapeShell(action)}`;
      break;
    case 'test':
      action = `display-message ${escapeShell(action)}`;
      break;
    case 'run':
      action = `run -b ${escapeShell(action)}`;
      break;
  }

  if (isModal) {
    action += ` \\; switch-client -T${tableName}`;
  }
  
  return action;
}

function escapeShell(cmd: string): string {
  return cmd.replace(/ /g, '\\ ');
}
